name = "youtube-music-party-backend"
main = "src/index.ts"
compatibility_date = "2026-06-02"

[[durable_objects.bindings]]
name = "PARTY_ROOMS"
class_name = "PartyRoom"

[[kv_namespaces]]
binding = "INVITES"
id = "3eafc67874fd4b2d938823b1f106dc37"
preview_id = "9922c5d5ace54a5b8fa72370f2a74a7d"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "fb7b637331294d10b438eb33bfc0ba58"
preview_id = "d3d5b61128614bafa18a793a014f4228"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PartyRoom"]
